customhost = "database-2.cguvf4ezgvcl.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "mickeyleeyongwai-employee"
customregion = "us-east-1"
